image: node:10.15.3

pipelines:
 default:
   - step:
       name: Install, Unit tests, e2e tests, Build
       caches:
         - node
       deployment: test
       script:
         - npm install
         - npm run build --prod
         - pipe: atlassian/firebase-deploy:0.3.0
           variables:
             FIREBASE_TOKEN: '$FIREBASE_TOKEN'
             PROJECT_ID: '$FIREBASE_PROJECT'